**Fake News Detection (LSTM)**

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/News.csv')

In [ ]:
df.head()

,Unnamed: 0,News Title,News Text,subject,News Date,Class
0,0.0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0.0
1,1.0,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0.0
2,2.0,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0.0
3,3.0,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0.0
4,4.0,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0.0

In [ ]:

df.isna().sum()

Unnamed: 0    0
News Title    0
News Text     0
subject       0
News Date     0
Class         0
dtype: int64

In [ ]:
#This is Used for Droping Non Values
df=df.dropna()

In [ ]:
X=df.drop('Class',axis=1)

In [ ]:
y=df['Class']

In [ ]:
X.shape

(44898, 5)

In [ ]:
y.shape

(44898,)

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.17.1'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
# Tokenizer setup
MAX_WORDS = 10000  # Top 10,000 most common words
tokenizer = Tokenizer(num_words=MAX_WORDS)
tokenizer.fit_on_texts(df['News Text'])

In [ ]:
voc_size = len(tokenizer.word_index) + 1
MAX_LEN = 200

Now One Hot Representation

In [ ]:
messages=X.copy()

In [ ]:
messages['News Title'][1]

' Drunk Bragging Trump Staffer Started Russian Collusion Investigation'

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['News Title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
39898
39899
39900
39901
39902
39903
39904
39905
39906
39907
39908
39909
39910
39911
39912
39913
39914
39915
39916
39917
39918
39919
39920
39921
39922
39923
39924
39925
39926
39927
39928
39929
39930
39931
39932
39933
39934
39935
39936
39937
39938
39939
39940
39941
39942
39943
39944
39945
39946
39947
39948
39949
39950
39951
39952
39953
39954
39955
39956
39957
39958
39959
39960
39961
39962
39963
39964
39965
39966
39967
39968
39969
39970
39971
39972
39973
39974
39975
39976
39977
39978
39979
39980
39981
39982
39983
39984
39985
39986
39987
39988
39989
39990
39991
39992
39993
39994
39995
39996
39997
39998
39999
40000
40001
40002
40003
40004
40005
40006
40007
40008
40009
40010
40011
40012
40013
40014
40015
40016
40017
40018
40019
40020
40021
40022
40023
40024
40025
40026
40027
40028
40029
40030
40031
40032
40033
40034
40035
40036
40037
40038
40039
40040
40041
40042
40043
40044
40045
40046
40047
40048
40049
40050
40051
40052
40053
40054
40055
40056
40057
40058
40059
40060
40061
40062
40063
40064
40065
40066
40067
40068
40069
40070
40071
40072
40073
40074
40075
40076
40077
40078
40079
40080
40081
40082
40083
40084
40085
40086
40087
40088
40089
40090
40091
40092
40093
40094
40095
40096
40097
40098
40099
40100
40101
40102
40103
40104
40105
40106
40107
40108
40109
40110
40111
40112
40113
40114
40115
40116
40117
40118
40119
40120
40121
40122
40123
40124
40125
40126
40127
40128
40129
40130
40131
40132
40133
40134
40135
40136
40137
40138
40139
40140
40141
40142
40143
40144
40145
40146
40147
40148
40149
40150
40151
40152
40153
40154
40155
40156
40157
40158
40159
40160
40161
40162
40163
40164
40165
40166
40167
40168
40169
40170
40171
40172
40173
40174
40175
40176
40177
40178
40179
40180
40181
40182
40183
40184
40185
40186
40187
40188
40189
40190
40191
40192
40193
40194
40195
40196
40197
40198
40199
40200
40201
40202
40203
40204
40205
40206
40207
40208
40209
40210
40211
40212
40213
40214
40215
40216
40217
40218
40219
40220
40221
40222
40223
40224
40225
40226
40227
40228
40229
40230
40231
40232
40233
40234
40235
40236
40237
40238
40239
40240
40241
40242
40243
40244
40245
40246
40247
40248
40249
40250
40251
40252
40253
40254
40255
40256
40257
40258
40259
40260
40261
40262
40263
40264
40265
40266
40267
40268
40269
40270
40271
40272
40273
40274
40275
40276
40277
40278
40279
40280
40281
40282
40283
40284
40285
40286
40287
40288
40289
40290
40291
40292
40293
40294
40295
40296
40297
40298
40299
40300
40301
40302
40303
40304
40305
40306
40307
40308
40309
40310
40311
40312
40313
40314
40315
40316
40317
40318
40319
40320
40321
40322
40323
40324
40325
40326
40327
40328
40329
40330
40331
40332
40333
40334
40335
40336
40337
40338
40339
40340
40341
40342
40343
40344
40345
40346
40347
40348
40349
40350
40351
40352
40353
40354
40355
40356
40357
40358
40359
40360
40361
40362
40363
40364
40365
40366
40367
40368
40369
40370
40371
40372
40373
40374
40375
40376
40377
40378
40379
40380
40381
40382
40383
40384
40385
40386
40387
40388
40389
40390
40391
40392
40393
40394
40395
40396
40397
40398
40399
40400
40401
40402
40403
40404
40405
40406
40407
40408
40409
40410
40411
40412
40413
40414
40415
40416
40417
40418
40419
40420
40421
40422
40423
40424
40425
40426
40427
40428
40429
40430
40431
40432
40433
40434
40435
40436
40437
40438
40439
40440
40441
40442
40443
40444
40445
40446
40447
40448
40449
40450
40451
40452
40453
40454
40455
40456
40457
40458
40459
40460
40461
40462
40463
40464
40465
40466
40467
40468
40469
40470
40471
40472
40473
40474
40475
40476
40477
40478
40479
40480
40481
40482
40483
40484
40485
40486
40487
40488
40489
40490
40491
40492
40493
40494
40495
40496
40497
40498
40499
40500
40501
40502
40503
40504
40505
40506
40507
40508
40509
40510
40511
40512
40513
40514
40515
40516
40517
40518
40519
40520
40521
40522
40523
40524
40525
40526
40527
40528
40529
40530
40531
40532
40533
40534
40535
40536
40537
40538
40539
40540
40541
40542
40543
40544
40545
40546
40547
40548
40549
40550
40551
40552
40553
40554
40555
40556
40557
40558
40559
40560
40561
40562
40563
40564
40565
40566
40567
40568
40569
40570
40571
40572
40573
40574
40575
40576
40577
40578
40579
40580
40581
40582
40583
40584
40585
40586
40587
40588
40589
40590
40591
40592
40593
40594
40595
40596
40597
40598
40599
40600
40601
40602
40603
40604
40605
40606
40607
40608
40609
40610
40611
40612
40613
40614
40615
40616
40617
40618
40619
40620
40621
40622
40623
40624
40625
40626
40627
40628
40629
40630
40631
40632
40633
40634
40635
40636
40637
40638
40639
40640
40641
40642
40643
40644
40645
40646
40647
40648
40649
40650
40651
40652
40653
40654
40655
40656
40657
40658
40659
40660
40661
40662
40663
40664
40665
40666
40667
40668
40669
40670
40671
40672
40673
40674
40675
40676
40677
40678
40679
40680
40681
40682
40683
40684
40685
40686
40687
40688
40689
40690
40691
40692
40693
40694
40695
40696
40697
40698
40699
40700
40701
40702
40703
40704
40705
40706
40707
40708
40709
40710
40711
40712
40713
40714
40715
40716
40717
40718
40719
40720
40721
40722
40723
40724
40725
40726
40727
40728
40729
40730
40731
40732
40733
40734
40735
40736
40737
40738
40739
40740
40741
40742
40743
40744
40745
40746
40747
40748
40749
40750
40751
40752
40753
40754
40755
40756
40757
40758
40759
40760
40761
40762
40763
40764
40765
40766
40767
40768
40769
40770
40771
40772
40773
40774
40775
40776
40777
40778
40779
40780
40781
40782
40783
40784
40785
40786
40787
40788
40789
40790
40791
40792
40793
40794
40795
40796
40797
40798
40799
40800
40801
40802
40803
40804
40805
40806
40807
40808
40809
40810
40811
40812
40813
40814
40815
40816
40817
40818
40819
40820
40821
40822
40823
40824
40825
40826
40827
40828
40829
40830
40831
40832
40833
40834
40835
40836
40837
40838
40839
40840
40841
40842
40843
40844
40845
40846
40847
40848
40849
40850
40851
40852
40853
40854
40855
40856
40857
40858
40859
40860
40861
40862
40863
40864
40865
40866
40867
40868
40869
40870
40871
40872
40873
40874
40875
40876
40877
40878
40879
40880
40881
40882
40883
40884
40885
40886
40887
40888
40889
40890
40891
40892
40893
40894
40895
40896
40897
40898
40899
40900
40901
40902
40903
40904
40905
40906
40907
40908
40909
40910
40911
40912
40913
40914
40915
40916
40917
40918
40919
40920
40921
40922
40923
40924
40925
40926
40927
40928
40929
40930
40931
40932
40933
40934
40935
40936
40937
40938
40939
40940
40941
40942
40943
40944
40945
40946
40947
40948
40949
40950
40951
40952
40953
40954
40955
40956
40957
40958
40959
40960
40961
40962
40963
40964
40965
40966
40967
40968
40969
40970
40971
40972
40973
40974
40975
40976
40977
40978
40979
40980
40981
40982
40983
40984
40985
40986
40987
40988
40989
40990
40991
40992
40993
40994
40995
40996
40997
40998
40999
41000
41001
41002
41003
41004
41005
41006
41007
41008
41009
41010
41011
41012
41013
41014
41015
41016
41017
41018
41019
41020
41021
41022
41023
41024
41025
41026
41027
41028
41029
41030
41031
41032
41033
41034
41035
41036
41037
41038
41039
41040
41041
41042
41043
41044
41045
41046
41047
41048
41049
41050
41051
41052
41053
41054
41055
41056
41057
41058
41059
41060
41061
41062
41063
41064
41065
41066
41067
41068
41069
41070
41071
41072
41073
41074
41075
41076
41077
41078
41079
41080
41081
41082
41083
41084
41085
41086
41087
41088
41089
41090
41091
41092
41093
41094
41095
41096
41097
41098
41099
41100
41101
41102
41103
41104
41105
41106
41107
41108
41109
41110
41111
41112
41113
41114
41115
41116
41117
41118
41119
41120
41121
41122
41123
41124
41125
41126
41127
41128
41129
41130
41131
41132
41133
41134
41135
41136
41137
41138
41139
41140
41141
41142
41143
41144
41145
41146
41147
41148
41149
41150
41151
41152
41153
41154
41155
41156
41157
41158
41159
41160
41161
41162
41163
41164
41165
41166
41167
41168
41169
41170
41171
41172
41173
41174
41175
41176
41177
41178
41179
41180
41181
41182
41183
41184
41185
41186
41187
41188
41189
41190
41191
41192
41193
41194
41195
41196
41197
41198
41199
41200
41201
41202
41203
41204
41205
41206
41207
41208
41209
41210
41211
41212
41213
41214
41215
41216
41217
41218
41219
41220
41221
41222
41223
41224
41225
41226
41227
41228
41229
41230
41231
41232
41233
41234
41235
41236
41237
41238
41239
41240
41241
41242
41243
41244
41245
41246
41247
41248
41249
41250
41251
41252
41253
41254
41255
41256
41257
41258
41259
41260
41261
41262
41263
41264
41265
41266
41267
41268
41269
41270
41271
41272
41273
41274
41275
41276
41277
41278
41279
41280
41281
41282
41283
41284
41285
41286
41287
41288
41289
41290
41291
41292
41293
41294
41295
41296
41297
41298
41299
41300
41301
41302
41303
41304
41305
41306
41307
41308
41309
41310
41311
41312
41313
41314
41315
41316
41317
41318
41319
41320
41321
41322
41323
41324
41325
41326
41327
41328
41329
41330
41331
41332
41333
41334
41335
41336
41337
41338
41339
41340
41341
41342
41343
41344
41345
41346
41347
41348
41349
41350
41351
41352
41353
41354
41355
41356
41357
41358
41359
41360
41361
41362
41363
41364
41365
41366
41367
41368
41369
41370
41371
41372
41373
41374
41375
41376
41377
41378
41379
41380
41381
41382
41383
41384
41385
41386
41387
41388
41389
41390
41391
41392
41393
41394
41395
41396
41397
41398
41399
41400
41401
41402
41403
41404
41405
41406
41407
41408
41409
41410
41411
41412
41413
41414
41415
41416
41417
41418
41419
41420
41421
41422
41423
41424
41425
41426
41427
41428
41429
41430
41431
41432
41433
41434
41435
41436
41437
41438
41439
41440
41441
41442
41443
41444
41445
41446
41447
41448
41449
41450
41451
41452
41453
41454
41455
41456
41457
41458
41459
41460
41461
41462
41463
41464
41465
41466
41467
41468
41469
41470
41471
41472
41473
41474
41475
41476
41477
41478
41479
41480
41481
41482
41483
41484
41485
41486
41487
41488
41489
41490
41491
41492
41493
41494
41495
41496
41497
41498
41499
41500
41501
41502
41503
41504
41505
41506
41507
41508
41509
41510
41511
41512
41513
41514
41515
41516
41517
41518
41519
41520
41521
41522
41523
41524
41525
41526
41527
41528
41529
41530
41531
41532
41533
41534
41535
41536
41537
41538
41539
41540
41541
41542
41543
41544
41545
41546
41547
41548
41549
41550
41551
41552
41553
41554
41555
41556
41557
41558
41559
41560
41561
41562
41563
41564
41565
41566
41567
41568
41569
41570
41571
41572
41573
41574
41575
41576
41577
41578
41579
41580
41581
41582
41583
41584
41585
41586
41587
41588
41589
41590
41591
41592
41593
41594
41595
41596
41597
41598
41599
41600
41601
41602
41603
41604
41605
41606
41607
41608
41609
41610
41611
41612
41613
41614
41615
41616
41617
41618
41619
41620
41621
41622
41623
41624
41625
41626
41627
41628
41629
41630
41631
41632
41633
41634
41635
41636
41637
41638
41639
41640
41641
41642
41643
41644
41645
41646
41647
41648
41649
41650
41651
41652
41653
41654
41655
41656
41657
41658
41659
41660
41661
41662
41663
41664
41665
41666
41667
41668
41669
41670
41671
41672
41673
41674
41675
41676
41677
41678
41679
41680
41681
41682
41683
41684
41685
41686
41687
41688
41689
41690
41691
41692
41693
41694
41695
41696
41697
41698
41699
41700
41701
41702
41703
41704
41705
41706
41707
41708
41709
41710
41711
41712
41713
41714
41715
41716
41717
41718
41719
41720
41721
41722
41723
41724
41725
41726
41727
41728
41729
41730
41731
41732
41733
41734
41735
41736
41737
41738
41739
41740
41741
41742
41743
41744
41745
41746
41747
41748
41749
41750
41751
41752
41753
41754
41755
41756
41757
41758
41759
41760
41761
41762
41763
41764
41765
41766
41767
41768
41769
41770
41771
41772
41773
41774
41775
41776
41777
41778
41779
41780
41781
41782
41783
41784
41785
41786
41787
41788
41789
41790
41791
41792
41793
41794
41795
41796
41797
41798
41799
41800
41801
41802
41803
41804
41805
41806
41807
41808
41809
41810
41811
41812
41813
41814
41815
41816
41817
41818
41819
41820
41821
41822
41823
41824
41825
41826
41827
41828
41829
41830
41831
41832
41833
41834
41835
41836
41837
41838
41839
41840
41841
41842
41843
41844
41845
41846
41847
41848
41849
41850
41851
41852
41853
41854
41855
41856
41857
41858
41859
41860
41861
41862
41863
41864
41865
41866
41867
41868
41869
41870
41871
41872
41873
41874
41875
41876
41877
41878
41879
41880
41881
41882
41883
41884
41885
41886
41887
41888
41889
41890
41891
41892
41893
41894
41895
41896
41897
41898
41899
41900
41901
41902
41903
41904
41905
41906
41907
41908
41909
41910
41911
41912
41913
41914
41915
41916
41917
41918
41919
41920
41921
41922
41923
41924
41925
41926
41927
41928
41929
41930
41931
41932
41933
41934
41935
41936
41937
41938
41939
41940
41941
41942
41943
41944
41945
41946
41947
41948
41949
41950
41951
41952
41953
41954
41955
41956
41957
41958
41959
41960
41961
41962
41963
41964
41965
41966
41967
41968
41969
41970
41971
41972
41973
41974
41975
41976
41977
41978
41979
41980
41981
41982
41983
41984
41985
41986
41987
41988
41989
41990
41991
41992
41993
41994
41995
41996
41997
41998
41999
42000
42001
42002
42003
42004
42005
42006
42007
42008
42009
42010
42011
42012
42013
42014
42015
42016
42017
42018
42019
42020
42021
42022
42023
42024
42025
42026
42027
42028
42029
42030
42031
42032
42033
42034
42035
42036
42037
42038
42039
42040
42041
42042
42043
42044
42045
42046
42047
42048
42049
42050
42051
42052
42053
42054
42055
42056
42057
42058
42059
42060
42061
42062
42063
42064
42065
42066
42067
42068
42069
42070
42071
42072
42073
42074
42075
42076
42077
42078
42079
42080
42081
42082
42083
42084
42085
42086
42087
42088
42089
42090
42091
42092
42093
42094
42095
42096
42097
42098
42099
42100
42101
42102
42103
42104
42105
42106
42107
42108
42109
42110
42111
42112
42113
42114
42115
42116
42117
42118
42119
42120
42121
42122
42123
42124
42125
42126
42127
42128
42129
42130
42131
42132
42133
42134
42135
42136
42137
42138
42139
42140
42141
42142
42143
42144
42145
42146
42147
42148
42149
42150
42151
42152
42153
42154
42155
42156
42157
42158
42159
42160
42161
42162
42163
42164
42165
42166
42167
42168
42169
42170
42171
42172
42173
42174
42175
42176
42177
42178
42179
42180
42181
42182
42183
42184
42185
42186
42187
42188
42189
42190
42191
42192
42193
42194
42195
42196
42197
42198
42199
42200
42201
42202
42203
42204
42205
42206
42207
42208
42209
42210
42211
42212
42213
42214
42215
42216
42217
42218
42219
42220
42221
42222
42223
42224
42225
42226
42227
42228
42229
42230
42231
42232
42233
42234
42235
42236
42237
42238
42239
42240
42241
42242
42243
42244
42245
42246
42247
42248
42249
42250
42251
42252
42253
42254
42255
42256
42257
42258
42259
42260
42261
42262
42263
42264
42265
42266
42267
42268
42269
42270
42271
42272
42273
42274
42275
42276
42277
42278
42279
42280
42281
42282
42283
42284
42285
42286
42287
42288
42289
42290
42291
42292
42293
42294
42295
42296
42297
42298
42299
42300
42301
42302
42303
42304
42305
42306
42307
42308
42309
42310
42311
42312
42313
42314
42315
42316
42317
42318
42319
42320
42321
42322
42323
42324
42325
42326
42327
42328
42329
42330
42331
42332
42333
42334
42335
42336
42337
42338
42339
42340
42341
42342
42343
42344
42345
42346
42347
42348
42349
42350
42351
42352
42353
42354
42355
42356
42357
42358
42359
42360
42361
42362
42363
42364
42365
42366
42367
42368
42369
42370
42371
42372
42373
42374
42375
42376
42377
42378
42379
42380
42381
42382
42383
42384
42385
42386
42387
42388
42389
42390
42391
42392
42393
42394
42395
42396
42397
42398
42399
42400
42401
42402
42403
42404
42405
42406
42407
42408
42409
42410
42411
42412
42413
42414
42415
42416
42417
42418
42419
42420
42421
42422
42423
42424
42425
42426
42427
42428
42429
42430
42431
42432
42433
42434
42435
42436
42437
42438
42439
42440
42441
42442
42443
42444
42445
42446
42447
42448
42449
42450
42451
42452
42453
42454
42455
42456
42457
42458
42459
42460
42461
42462
42463
42464
42465
42466
42467
42468
42469
42470
42471
42472
42473
42474
42475
42476
42477
42478
42479
42480
42481
42482
42483
42484
42485
42486
42487
42488
42489
42490
42491
42492
42493
42494
42495
42496
42497
42498
42499
42500
42501
42502
42503
42504
42505
42506
42507
42508
42509
42510
42511
42512
42513
42514
42515
42516
42517
42518
42519
42520
42521
42522
42523
42524
42525
42526
42527
42528
42529
42530
42531
42532
42533
42534
42535
42536
42537
42538
42539
42540
42541
42542
42543
42544
42545
42546
42547
42548
42549
42550
42551
42552
42553
42554
42555
42556
42557
42558
42559
42560
42561
42562
42563
42564
42565
42566
42567
42568
42569
42570
42571
42572
42573
42574
42575
42576
42577
42578
42579
42580
42581
42582
42583
42584
42585
42586
42587
42588
42589
42590
42591
42592
42593
42594
42595
42596
42597
42598
42599
42600
42601
42602
42603
42604
42605
42606
42607
42608
42609
42610
42611
42612
42613
42614
42615
42616
42617
42618
42619
42620
42621
42622
42623
42624
42625
42626
42627
42628
42629
42630
42631
42632
42633
42634
42635
42636
42637
42638
42639
42640
42641
42642
42643
42644
42645
42646
42647
42648
42649
42650
42651
42652
42653
42654
42655
42656
42657
42658
42659
42660
42661
42662
42663
42664
42665
42666
42667
42668
42669
42670
42671
42672
42673
42674
42675
42676
42677
42678
42679
42680
42681
42682
42683
42684
42685
42686
42687
42688
42689
42690
42691
42692
42693
42694
42695
42696
42697
42698
42699
42700
42701
42702
42703
42704
42705
42706
42707
42708
42709
42710
42711
42712
42713
42714
42715
42716
42717
42718
42719
42720
42721
42722
42723
42724
42725
42726
42727
42728
42729
42730
42731
42732
42733
42734
42735
42736
42737
42738
42739
42740
42741
42742
42743
42744
42745
42746
42747
42748
42749
42750
42751
42752
42753
42754
42755
42756
42757
42758
42759
42760
42761
42762
42763
42764
42765
42766
42767
42768
42769
42770
42771
42772
42773
42774
42775
42776
42777
42778
42779
42780
42781
42782
42783
42784
42785
42786
42787
42788
42789
42790
42791
42792
42793
42794
42795
42796
42797
42798
42799
42800
42801
42802
42803
42804
42805
42806
42807
42808
42809
42810
42811
42812
42813
42814
42815
42816
42817
42818
42819
42820
42821
42822
42823
42824
42825
42826
42827
42828
42829
42830
42831
42832
42833
42834
42835
42836
42837
42838
42839
42840
42841
42842
42843
42844
42845
42846
42847
42848
42849
42850
42851
42852
42853
42854
42855
42856
42857
42858
42859
42860
42861
42862
42863
42864
42865
42866
42867
42868
42869
42870
42871
42872
42873
42874
42875
42876
42877
42878
42879
42880
42881
42882
42883
42884
42885
42886
42887
42888
42889
42890
42891
42892
42893
42894
42895
42896
42897
42898
42899
42900
42901
42902
42903
42904
42905
42906
42907
42908
42909
42910
42911
42912
42913
42914
42915
42916
42917
42918
42919
42920
42921
42922
42923
42924
42925
42926
42927
42928
42929
42930
42931
42932
42933
42934
42935
42936
42937
42938
42939
42940
42941
42942
42943
42944
42945
42946
42947
42948
42949
42950
42951
42952
42953
42954
42955
42956
42957
42958
42959
42960
42961
42962
42963
42964
42965
42966
42967
42968
42969
42970
42971
42972
42973
42974
42975
42976
42977
42978
42979
42980
42981
42982
42983
42984
42985
42986
42987
42988
42989
42990
42991
42992
42993
42994
42995
42996
42997
42998
42999
43000
43001
43002
43003
43004
43005
43006
43007
43008
43009
43010
43011
43012
43013
43014
43015
43016
43017
43018
43019
43020
43021
43022
43023
43024
43025
43026
43027
43028
43029
43030
43031
43032
43033
43034
43035
43036
43037
43038
43039
43040
43041
43042
43043
43044
43045
43046
43047
43048
43049
43050
43051
43052
43053
43054
43055
43056
43057
43058
43059
43060
43061
43062
43063
43064
43065
43066
43067
43068
43069
43070
43071
43072
43073
43074
43075
43076
43077
43078
43079
43080
43081
43082
43083
43084
43085
43086
43087
43088
43089
43090
43091
43092
43093
43094
43095
43096
43097
43098
43099
43100
43101
43102
43103
43104
43105
43106
43107
43108
43109
43110
43111
43112
43113
43114
43115
43116
43117
43118
43119
43120
43121
43122
43123
43124
43125
43126
43127
43128
43129
43130
43131
43132
43133
43134
43135
43136
43137
43138
43139
43140
43141
43142
43143
43144
43145
43146
43147
43148
43149
43150
43151
43152
43153
43154
43155
43156
43157
43158
43159
43160
43161
43162
43163
43164
43165
43166
43167
43168
43169
43170
43171
43172
43173
43174
43175
43176
43177
43178
43179
43180
43181
43182
43183
43184
43185
43186
43187
43188
43189
43190
43191
43192
43193
43194
43195
43196
43197
43198
43199
43200
43201
43202
43203
43204
43205
43206
43207
43208
43209
43210
43211
43212
43213
43214
43215
43216
43217
43218
43219
43220
43221

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[54654, 15901, 84785, 86917, 79562, 107082, 104085, 77518, 2806],
 [53939, 88912, 15901, 134017, 100417, 116355, 67994, 121569],
 [59557, 79207, 38770, 67379, 52323, 116416, 3257, 124870, 40490, 129246],
 [15901, 95869, 35567, 114201, 95818, 134571, 57133, 1699],
 [81279, 114373, 102023, 54654, 15901, 129141, 122582],
 [27314, 53704, 48482, 108596, 96570, 68430, 15362, 99661, 1699],
 [8668, 109080, 92141, 15901, 75362, 24243, 112186, 58480, 53249, 136416],
 [15901, 35532, 89157, 27314, 14593, 114882, 60356, 60559, 124371, 124409],
 [12718,
  133165,
  58480,
  7152,
  15901,
  121202,
  45871,
  27059,
  91702,
  38486,
  26627,
  110009,
  125170],
 [23951, 99196, 79562, 57928, 15901, 509, 14208, 133041, 23488, 22601, 118028],
 [67675, 47360, 22848, 65643, 61113, 99367, 129912, 61495],
 [23951, 97079, 73634, 40559, 43848, 4593, 48595, 45135, 7392, 11070, 64818],
 [129912, 58480, 15901, 102524, 5320, 45761, 131606, 59851],
 [23951, 125007, 1265, 121827, 76918, 46426, 15901, 104198, 54879, 114375],
 [118119, 13502, 102294, 72797, 110321, 122109, 43848, 9846, 12757, 70325],
 [88001, 72280, 15901, 37917, 33202, 101887, 17169, 50287, 80796, 32874],
 [52323, 108596, 67580, 13502, 79562, 15901, 125692, 22448, 34739],
 [58341, 111750, 44218, 79606, 54654, 15901, 129141],
 [62015,
  49931,
  67580,
  32202,
  137532,
  71105,
  3775,
  89911,
  17169,
  42911,
  136897,
  103713,
  73937],
 [97602, 136897, 77123, 75504, 7678, 25917, 58341],
 [96620,
  46711,
  68267,
  15901,
  16303,
  82982,
  28411,
  83065,
  52135,
  40991,
  126138],
 [64373,
  110321,
  64818,
  33202,
  103223,
  51556,
  35969,
  71105,
  26002,
  60048,
  37627],
 [39329,
  54151,
  125170,
  100238,
  9741,
  121341,
  67765,
  127342,
  84802,
  12734,
  53704],
 [2307, 102023, 89046, 116312, 53704, 136897, 27431, 67055, 107082],
 [4711, 44039, 67799, 15901, 82573, 136835, 19663, 121111, 28938, 73937],
 [14918, 15901, 91702, 123993, 136897, 43477, 103330, 10053, 77324, 125170],
 [32202, 137532, 71105, 136897, 29669, 3775, 89911, 3183, 67748, 19042, 73937],
 [23951, 79329, 129727, 102023, 14897, 24243, 68997, 16899, 121569, 15901],
 [86772, 88858, 119586, 15901, 3775, 89911, 62247, 119926, 1595, 84623, 73937],
 [8690, 81407, 67580, 42911, 63186, 32083, 33211, 45967],
 [68461,
  48482,
  15810,
  77123,
  121288,
  57531,
  16652,
  135831,
  19730,
  19849,
  37627],
 [23951, 55092, 15901, 80989, 107191],
 [15901, 112473, 134298, 64211, 130026, 131444, 108778, 69659, 42579],
 [15901, 4593, 15901, 58167, 59363, 109262],
 [23951,
  15901,
  46665,
  35118,
  36894,
  106392,
  15901,
  110089,
  104189,
  35118,
  48514,
  16671],
 [92896, 110321, 136897, 8266, 95770, 53704, 89046, 136897, 1699],
 [97602, 110757, 3940, 132056, 92108, 89046, 132428, 136897],
 [54654, 15901, 114011, 33139, 5755, 36603, 106796, 105702, 95707],
 [47360, 54151, 136355, 69659, 89229, 104259, 107822, 33211, 86627, 125170],
 [61721, 71708, 111592, 125170, 64446, 24243, 106845, 61407],
 [24243, 135256, 135867, 54654, 15901, 64446, 74851, 53249, 136416],
 [70068,
  124371,
  127664,
  49931,
  62015,
  135207,
  29329,
  15901,
  56376,
  28242,
  26626,
  73937],
 [64288, 84608, 23116, 15901, 60693, 60711, 84518, 90865, 3907, 133390, 15901],
 [15901, 136808, 72571, 14794, 96116, 24243, 5237, 136416, 61622, 121569],
 [23951,
  95438,
  128549,
  131659,
  14794,
  99392,
  25620,
  100804,
  53362,
  71234,
  73937],
 [4711, 44039, 110764, 72797, 14794, 7678, 29329],
 [68461, 131659, 14794, 13078, 79775, 58341, 15901],
 [15901, 77123, 67970, 44218, 128520, 119279, 4711, 57503, 99103],
 [49931, 10053, 509, 92320, 22986, 134576, 72175, 133390, 60693],
 [103143, 34136, 23730, 15901, 106943, 17169, 79565, 73937],
 [87498,
  38531,
  25917,
  58341,
  60559,
  114701,
  71823,
  110334,
  53479,
  109105,
  20958],
 [15901,
  84785,
  34241,
  67055,
  125170,
  44011,
  45340,
  17169,
  49955,
  25349,
  106681,
  37902],
 [11166, 133390, 34739, 32202, 37717, 107082, 50380, 60048],
 [15901, 55180, 77736, 79357, 124409, 39290, 36129, 78917, 125170, 88262],
 [15901, 99692, 127815, 99103, 4711, 57503, 131213, 102248],
 [96618, 89275, 58819, 107657, 34305, 114401, 126509, 42196, 1699],
 [89046, 60732, 15901, 32870, 44218, 128520, 64446, 89157, 89229, 83580],
 [15901, 79774, 115283, 96570, 40490, 125622, 64223, 86079, 98496],
 [15901, 46665, 45762, 130437, 90590, 87371, 247, 37034, 15177, 125170],
 [114427,
  45992,
  11166,
  134571,
  55283,
  15901,
  102023,
  9691,
  126501,
  38706,
  73937],
 [57928,
  15901,
  88858,
  97787,
  126340,
  114201,
  62247,
  22601,
  15901,
  12929,
  80158],
 [108532,
  57901,
  2307,
  129727,
  30005,
  72656,
  76348,
  23116,
  3775,
  89911,
  37654,
  73937],
 [12718, 114201, 133530, 29329, 119586, 15901, 80224, 79562, 35393, 125170],
 [124409, 109080, 12254, 15901, 45761, 52643, 34739, 93915],
 [30807, 109105, 133390, 15901, 103059, 94032, 32202, 137532, 71105, 12757],
 [53397, 62026, 97602, 35248, 24027, 69328, 35144],
 [15901, 983, 100651, 45761, 75391, 92209, 12878, 134850, 82900],
 [2307, 5180, 15901, 64446, 129912, 55648, 16671, 125170],
 [96618, 89275, 77123, 21844, 75277, 67055, 105367, 102023, 15901, 96116],
 [67055, 105367, 115734, 15901, 96116, 68212],
 [45309,
  94032,
  101064,
  114201,
  64446,
  12399,
  79357,
  64573,
  12929,
  26627,
  130887],
 [129671, 136709, 89157, 33907, 122258, 121919, 47360, 54151, 20772],
 [58026,
  110321,
  82902,
  13285,
  121341,
  67765,
  2554,
  33360,
  3775,
  89911,
  136897,
  103713,
  73937],
 [23951,
  65643,
  53704,
  48482,
  40559,
  120409,
  3775,
  89911,
  20352,
  26847,
  82210,
  129417],
 [79562, 9460, 67055, 56820, 53592, 116355, 135256, 68818, 134571, 95818],
 [79329, 58480, 55778, 127387, 99399, 114115, 16885, 77005, 83675],
 [23951, 102777, 111284, 29329, 15901, 65019, 124409, 92108, 89911],
 [64537, 53362, 23295, 5463, 94032, 3775, 89911, 136355, 26002, 60048, 110242],
 [15901, 110757, 8500, 4244, 13644, 121827, 67970],
 [15901, 71304, 58480, 5395, 81407, 63970, 63964, 43112, 77123, 14054, 97299],
 [58442, 30602, 137120, 15901, 91845],
 [42163, 37017, 106681, 135734, 44297, 4439, 40753, 97602, 126169],
 [110321,
  136897,
  1738,
  86845,
  58383,
  121827,
  83065,
  3775,
  89911,
  54654,
  15901,
  73937],
 [54654, 15901, 135867, 66842, 34783, 55092],
 [15901, 53286, 95243, 53747, 51496, 79562, 116693, 123993, 30988, 126701],
 [107424, 79622, 12115, 127442, 116666, 27279, 70377, 28826, 95707, 27816],
 [79562, 32202, 38531, 53286, 3775, 89911, 55778, 132384, 73937],
 [3775, 89911, 5237, 40490, 109499, 76918, 77123, 119586, 43417, 125170],
 [15901, 21253, 135436, 69659, 114201, 50330, 19015, 35567, 65081, 65495],
 [52323, 125344, 115339, 127442, 99103, 102023, 15901, 32083],
 [36129,
  58026,
  110321,
  33202,
  77123,
  73575,
  48445,
  67549,
  12115,
  64818,
  60559],
 [67055, 15901, 67580, 20076, 39920, 98822, 135155, 86232, 124409, 110591],
 [23951,
  14342,
  36894,
  85801,
  15901,
  49215,
  4244,
  110531,
  110321,
  12757,
  54662],
 [58442, 59557, 3257, 101826, 52897, 94397, 36129, 15901, 130659, 103688],
 [23951,
  121105,
  15901,
  79357,
  75362,
  79329,
  129727,
  56820,
  112911,
  111019,
  129756,
  32553],
 [3775, 89911, 46665, 97602, 17169, 102023, 35253],
 [63539, 15901, 40559, 18735, 114201, 14987, 66932, 129756, 134850, 82900],
 [107082,
  50380,
  125170,
  54654,
  15901,
  92320,
  43848,
  15884,
  78420,
  3775,
  89911],
 [131237, 15901, 94325, 8775, 88597, 68818, 105297, 4711, 44039, 106185],
 [15901,
  97445,
  2938,
  106681,
  102023,
  111191,
  102331,
  66842,
  111191,
  123337,
  48444],
 [23951, 103143, 23778, 21844, 15901, 121776, 114375, 49931],
 [73575, 64288, 121919, 23116, 15901, 74680, 71338, 77324, 116355, 99847],
 [78420,
  110321,
  64818,
  33202,
  398,
  18268,
  81407,
  66932,
  43397,
  26545,
  3710,
  135672],
 [3775, 89911, 12718, 51465, 72571, 26627, 121420, 132648, 60048],
 [23951, 37017, 24027, 22848, 135555, 46665, 16968, 44297, 105199],
 [42163, 37017, 106681, 94032, 92108, 110321, 29669, 3775, 89911],
 [15901,
  58819,
  129152,
  133839,
  34256,
  3183,
  67748,
  122637,
  8821,
  61913,
  116355,
  21203],
 [50380, 120450, 47040, 125170, 4187, 96031, 101981, 70489, 137604, 97965],
 [96618, 89275, 35532, 137532, 71105, 48147, 20395, 73937],
 [128736, 104451, 119926, 97883, 93915, 40490, 25294],
 [53704, 97602, 94032, 293, 97787, 42526],
 [110321, 136897, 29669, 133998, 96669, 137532, 71105],
 [136897, 89046, 69952, 54381, 47508, 110321, 124409, 4328, 15901, 94039],
 [67189, 1544, 58442, 59011, 13896, 76479, 75412, 23537, 43848, 68628, 116666],
 [96618,
  89275,
  46467,
  54088,
  60474,
  131227,
  127815,
  39856,
  20497,
  15901,
  50424,
  67031],
 [118642, 22986, 88597, 15901, 7678, 44218, 128520, 17602, 119040, 59851],
 [23951, 934, 70165, 61466, 15901, 29329, 9741, 45960, 52505],
 [15901, 134752, 115734, 100308, 133390, 58819, 13766, 43383, 34256],
 [13885, 100720, 15901, 34413, 44218, 128520, 133390, 127815],
 [15901,
  110177,
  100726,
  109630,
  65000,
  96516,
  97445,
  131514,
  61622,
  33269,
  116684],
 [15901,
  8690,
  53362,
  23295,
  35128,
  89229,
  135654,
  44011,
  60939,
  100308,
  133390],
 [15901, 27059, 102023, 134515, 25349, 54399, 73937],
 [131237, 15901, 98537, 40490, 26627, 77656, 53744, 23616, 66842],
 [61799, 58442, 100720, 43, 60455, 5237, 15901, 97602, 64223],
 [15901, 81407, 22601, 63176, 60732, 136161, 4655, 40490, 107522],
 [77546, 124371, 38531, 39087, 39087, 12878, 2499],
 [79329, 58480, 112473, 12365, 110718, 47980, 66659, 38847, 54654, 15901],
 [15901, 88597, 60067, 7999, 134850, 72571, 91375, 66842, 25349],
 [119114, 42163, 64275, 60455, 68267, 15781, 99338, 77123, 3605],
 [73216, 58442, 114840, 66274, 115734, 16968, 12721, 5755, 100417, 37698],
 [116355,
  136714,
  61622,
  90911,
  54654,
  15901,
  8690,
  35969,
  100717,
  76461,
  41358,
  41866],
 [23951, 97602, 126169, 127057, 66932, 119314, 47762, 43397, 119356],
 [107637, 81407, 110926, 32767, 13785, 89229, 1964, 60939],
 [136897, 30049, 52982, 46711, 110321, 51465, 129756, 110718],
 [100460, 133041, 82982, 99692, 15901, 79774, 69659, 68628, 116666],
 [40490, 48444, 58442, 68628, 116666, 15901, 9741, 61161, 27314],
 [15901, 122477, 18604, 45967, 23116, 72797, 22978, 115018, 108623],
 [128301,
  125418,
  15901,
  68310,
  110757,
  8500,
  4244,
  51475,
  67333,
  112290,
  58341],
 [12718, 56848, 123230, 58341, 5755, 33821, 15901, 84518],
 [110321,
  126169,
  64383,
  41383,
  119356,
  129756,
  19078,
  74246,
  13832,
  83580,
  73937],
 [4657, 108994, 125507, 73539, 15901, 84834],
 [15901, 136355, 87702, 71234, 31302, 136714, 127342, 33269, 94039],
 [37376,
  45309,
  15901,
  115734,
  102023,
  65516,
  44297,
  16885,
  39646,
  12399,
  18604],
 [5638, 62338, 67549, 509, 67675, 47360, 77123, 121783, 119628, 16968],
 [120450,
  47040,
  77123,
  78686,
  24594,
  60559,
  123950,
  24712,
  57116,
  60755,
  9853,
  73937],
 [30807, 114375, 110321, 14498, 136808, 60455, 18284],
 [129756, 22833, 104451, 54654, 15901, 110764, 104451, 89229, 35254, 37627],
 [61721, 71708, 111592, 9846, 64026, 67055, 110531, 87909, 76687],
 [15901, 117649, 46035, 101437, 64573, 44297, 4439, 89157],
 [93867, 49464, 45388, 137604, 116355, 36244, 32877],
 [17543,
  24027,
  4711,
  44039,
  56820,
  77123,
  8598,
  15779,
  125170,
  56820,
  100443,
  39270,
  54399],
 [67675,
  47360,
  64446,
  62338,
  27431,
  81873,
  49955,
  127506,
  102468,
  17169,
  24032,
  114474],
 [15901, 101178, 106886, 33269, 33376, 14681, 120409, 39555, 70124],
 [15177, 18854, 12908, 15901, 111705, 133874, 15901, 97079, 71061],
 [12718, 131568, 32202, 15901, 130003, 78897, 24712, 67055, 7999, 50424],
 [15901, 58819, 71823, 110334, 34256, 58341, 67333],
 [116355, 8598, 116390, 42163, 117180, 66497, 84017, 33294],
 [126101, 107482, 25441, 15901, 62151, 14681, 64446],
 [23951,
  110321,
  136897,
  80796,
  118600,
  11166,
  18664,
  86612,
  67333,
  120989,
  73937],
 [23951,
  15901,
  89259,
  77005,
  47360,
  7352,
  136808,
  117452,
  103330,
  44011,
  42295],
 [91794, 133839, 82210, 15901, 136714, 127057, 67994, 92188],
 [23951, 89275, 17169, 49955, 105023, 66497, 34739, 6759, 130555, 83580],
 [5490, 108028, 92819, 61020, 18761, 31973, 73937],
 [89275, 125170, 26627, 74047, 124409, 15901],
 [49955, 127506, 127878, 81683, 45309, 15901],
 [98496,
  26626,
  97079,
  71061,
  934,
  86425,
  37215,
  98496,
  27102,
  116355,
  67994,
  72175,
  125170,
  73937],
 [79329,
  58480,
  84987,
  58480,
  16899,
  105996,
  97883,
  67333,
  15901,
  116081,
  71536],
 [27314, 126237, 93112, 103102, 4711, 4711, 92188, 75628],
 [54151, 119926, 97445, 107082, 5237, 54654, 15901],
 [41866, 15901, 113013, 19164, 67333, 58341, 5755, 33211, 32870, 84623],
 [35248, 15901, 118041, 3867, 58341, 70124, 84518, 29288],
 [65919, 64818, 77539, 101178, 45761, 59851, 110373, 15901, 85188],
 [66497, 49931, 84053, 79329, 129727, 89157, 95869, 12464, 73937],
 [52323, 21844, 67365, 47278, 15093, 25572, 130003, 132428, 18664, 134571],
 [85546, 15901, 110764, 58341, 121569, 125418],
 [66497,
  6759,
  12773,
  20423,
  67333,
  41962,
  15901,
  32870,
  118389,
  51475,
  103688],
 [89229, 55778, 25717, 15901, 89521, 3257, 111191, 103688],
 [12929, 84623, 119858, 15901, 56428, 1699],
 [68461, 27431, 47116, 136506, 58341, 84518, 121569],
 [15901,
  35618,
  21531,
  5653,
  30807,
  12115,
  117649,
  79405,
  89019,
  44218,
  128520],
 [23951, 12718, 4711, 44039, 60693, 91702, 89275, 66497, 6759, 80025],
 [15901, 125418, 60559, 80377, 84518, 21245],
 [91728, 69659, 130770, 8147, 13133, 117780, 129931, 73937],
 [137354, 1636, 64423, 42763, 47762, 107082, 86914, 90337, 32083],
 [15901, 53286, 55778, 67216, 88747, 49567],
 [47360, 65751, 108994, 127878, 77518, 66497, 15901, 64223, 125170],
 [84751, 56725, 88597, 128019, 129313, 105297, 77621, 109105, 58026, 46951],
 [15901,
  8078,
  116377,
  64573,
  121723,
  29329,
  107082,
  50380,
  60048,
  76850,
  23457,
  28555],
 [17543, 24027, 15901, 10947, 17169, 49955, 17026, 12399, 102023, 16968],
 [23951,
  33014,
  60711,
  79405,
  37254,
  76687,
  84623,
  121919,
  15901,
  133874,
  125170],
 [49567, 15901, 25405, 34054, 3183, 129246, 88597, 96570, 135424, 117524],
 [15901,
  17009,
  102810,
  111809,
  66371,
  66371,
  24819,
  4711,
  44039,
  20162,
  77005],
 [110321, 136897, 29669, 45761, 135424, 48444, 52135, 40991, 64275, 29347],
 [23951, 47360, 54151, 67580, 34739, 61120, 19206, 129174, 4093],
 [32801,
  70328,
  15810,
  93014,
  104451,
  32486,
  35567,
  15901,
  102023,
  31336,
  45967],
 [83785, 34968, 31892, 96396, 76621, 64223, 90209, 67549, 57020, 71536],
 [15901, 115283, 89229, 42763, 17238, 79329, 58480],
 [15901, 47360, 7352, 53286, 133744, 25136, 78362, 114427, 125606, 73937],
 [82982,
  83245,
  38125,
  509,
  102023,
  15901,
  107522,
  101754,
  26122,
  51818,
  81292,
  73937],
 [15901,
  29329,
  3426,
  83245,
  24211,
  136506,
  70325,
  108445,
  91676,
  107082,
  20958],
 [70325, 111531, 29329, 15901, 96116, 89259, 77005, 5180, 46711, 73937],
 [23951, 56820, 75504, 61721, 71708, 111592, 76687, 112911, 123174, 73937],
 [67786,
  97883,
  17374,
  77123,
  67409,
  51475,
  34588,
  16968,
  62247,
  137318,
  73937],
 [15901, 77123, 51496, 29861, 126169, 96116, 25530, 92188, 16564, 54775],
 [15901,
  88912,
  134064,
  58857,
  121554,
  91728,
  2499,
  72370,
  116802,
  100081,
  77763],
 [14415,
  56771,
  38125,
  17230,
  22247,
  120409,
  54243,
  97445,
  16968,
  9027,
  107657],
 [4550,
  100308,
  15093,
  70444,
  17631,
  20710,
  27314,
  25572,
  39617,
  14208,
  66729,
  114201,
  73937],
 [79562,
  56820,
  23116,
  22986,
  31987,
  51496,
  15901,
  125848,
  1595,
  80224,
  133390],
 [23951, 19843, 4550, 33694, 102023, 15901, 46665, 4711, 114856],
 [15779, 49567, 15901, 33907, 122258, 29329, 52323, 97986, 983],
 [15901,
  115734,
  75312,
  44908,
  124409,
  64446,
  32801,
  64423,
  38531,
  88659,
  50951,
  102023],
 [15901,
  72184,
  26627,
  3710,
  89358,
  89229,
  62338,
  89046,
  88597,
  7678,
  44218,
  128520],
 [15901,
  15810,
  30049,
  65780,
  50951,
  102023,
  32801,
  27279,
  45761,
  96669,
  110470,
  93915],
 [64275, 18326, 7803, 114958, 49931, 126722, 105018, 64392, 54654, 15901],
 [5531,
  94032,
  60693,
  27279,
  41323,
  89674,
  83580,
  19898,
  45761,
  40490,
  65374,
  6043,
  129912],
 [54151, 82512, 46031, 44218, 128520, 60732, 15901, 131987],
 [12115, 80358, 110757, 20083, 112083, 117452, 11166, 18664, 761, 3510],
 [6043,
  50920,
  60371,
  76918,
  73937,
  120849,
  15901,
  88912,
  61403,
  86845,
  132648],
 [25917,
  114516,
  53901,
  2670,
  94854,
  18761,
  85351,
  109759,
  104106,
  54654,
  15901],
 [60647,
  99339,
  119586,
  36129,
  58026,
  99035,
  60104,
  127878,
  106230,
  35185,
  73937],
 [37125, 46711, 15901, 95071, 71625, 27431, 81873, 65366, 114401],
 [43402, 15901, 81739, 26626, 80224, 45135, 112473, 42397, 127878],
 [23951,
  10532,
  67765,
  124454,
  89157,
  97602,
  117452,
  15901,
  107424,
  43397,
  104945],
 [5869, 94397, 83516, 15901, 97621, 2949, 14257, 77123, 12464],
 [15901, 94039, 81407, 272, 103140, 8080, 91728, 35669, 86627, 1699],
 [72184, 62338, 70861, 15901, 97445, 116416, 126600, 95723],
 [4711,
  57928,
  15901,
  64537,
  81407,
  84288,
  64446,
  719,
  44218,
  61878,
  49931,
  73937],
 [35618, 21531, 30602, 8519, 43397, 15901, 3257, 23801, 57951, 94738],
 [15901, 15810, 100581, 38929, 133839, 27431, 122582, 32331, 88858, 34739],
 [15901, 104451, 25717, 131987, 18735, 3739, 109174, 9741, 108994, 73937],
 [23951, 44039, 77105, 8266, 114400, 100417, 12464, 103952, 15901],
 [15901, 3257, 70124, 109684, 45427, 88262, 75780, 125497],
 [4711, 44039, 38531, 94859, 16968, 32716, 95566, 35567, 22288, 104306, 72571],
 [3894, 16671, 30049, 124537, 135155, 46189, 35618, 21531],
 [15901, 5237, 81419, 136161, 93915, 109988, 26998, 109286, 112290],
 [110321, 126169, 97602, 25294, 112083, 4711, 44039, 73937],
 [15901, 93112, 89229, 114401, 23116, 48965, 80989, 34739],
 [96570,
  12115,
  113015,
  16968,
  57928,
  15901,
  62247,
  11061,
  48482,
  47116,
  92188],
 [66371, 131227, 114375, 60939, 4593, 4365, 86332, 107054],
 [47040,
  109988,
  15901,
  62338,
  27743,
  74266,
  21982,
  92386,
  58400,
  114840,
  108596,
  117780],
 [17883, 136897, 29669, 2499, 2499, 101004, 104306],
 [23951,
  79329,
  47489,
  3125,
  111284,
  133744,
  82982,
  126661,
  79562,
  129756,
  96116,
  28826,
  51641],
 [30155, 110321, 136897, 5180, 8270, 20162, 57986, 15901, 4711, 44039, 125170],
 [129756, 15901, 38273, 40490, 32343, 35778, 108596, 4439],
 [16968, 72184, 25938, 83245, 36129, 16968, 73937, 92386, 73937, 125170],
 [79562,
  46299,
  15901,
  125809,
  3415,
  69404,
  116666,
  7664,
  77324,
  10053,
  125170],
 [35778,
  16968,
  29082,
  80607,
  84851,
  5531,
  69659,
  61466,
  89889,
  62247,
  125170,
  1699],
 [42163,
  22961,
  129922,
  73284,
  137354,
  81345,
  106634,
  34790,
  59189,
  68267,
  137532],
 [15901, 72184, 8613, 127815, 129727, 22601, 116416, 32202, 6028, 89046],
 [15901, 49764, 110321, 123485, 40995, 124409, 42188, 126101, 2096],
 [52323, 118488, 39199, 133530, 64250, 65106, 15901, 108857],
 [23951,
  120450,
  47040,
  126509,
  49694,
  35618,
  21531,
  67511,
  122477,
  37034,
  44011,
  73937],
 [41772,
  40490,
  47508,
  100962,
  60048,
  10317,
  70907,
  80528,
  36129,
  20510,
  83065],
 [15901,
  66274,
  65471,
  72663,
  57116,
  45761,
  35618,
  21531,
  15779,
  127854,
  73937],
 [75312, 134017, 31892, 15901, 30113, 97986, 201, 23116, 38935, 73937],
 [102670, 15901, 132428, 119356, 88514, 16671, 27431, 67055, 107082],
 [2117,
  48482,
  48444,
  32486,
  122799,
  116666,
  124409,
  40862,
  88743,
  35567,
  56677],
 [36129, 41383, 97602, 41383, 60559],
 [110177, 93486, 35532, 91794, 116152, 73373, 40490],

**Embedding Representation**

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[     0      0      0 ... 104085  77518   2806]
 [     0      0      0 ... 116355  67994 121569]
 [     0      0      0 ... 124870  40490 129246]
 ...
 [     0      0      0 ...  98252  67379  26248]
 [     0      0      0 ... 114373  50424  84518]
 [     0      0      0 ...  66304 116355 101189]]

In [ ]:
embedded_docs[0]

array([     0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,  54654,  15901,  84785,  86917,  79562,
       107082, 104085,  77518,   2806], dtype=int32)

In [ ]:
#Creating Model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))

In [ ]:
#Complile the model
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)              │ (32, 20, 40)                │       5,504,520 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (32, 20, 40)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_3 (LSTM)                        │ (32, 100)                   │          56,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_3 (Dropout)                  │ (32, 100)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (32, 1)                     │             101 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,561,021 (21.21 MB)

 Trainable params: 5,561,021 (21.21 MB)

 Non-trainable params: 0 (0.00 B)

None

In [ ]:
len(embedded_docs)

44898

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((44898, 20), (44898,))

In [ ]:
sequences = tokenizer.texts_to_sequences(df['News Text'])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

**Model Training**

In [ ]:
#Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 46s 92ms/step - accuracy: 0.8392 - loss: 0.3249 - val_accuracy: 0.9515 - val_loss: 0.1236
Epoch 2/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 40s 86ms/step - accuracy: 0.9689 - loss: 0.0845 - val_accuracy: 0.9533 - val_loss: 0.1295
Epoch 3/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 43s 91ms/step - accuracy: 0.9811 - loss: 0.0508 - val_accuracy: 0.9525 - val_loss: 0.1378
Epoch 4/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 42s 88ms/step - accuracy: 0.9903 - loss: 0.0290 - val_accuracy: 0.9513 - val_loss: 0.1663
Epoch 5/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 83s 90ms/step - accuracy: 0.9940 - loss: 0.0187 - val_accuracy: 0.9485 - val_loss: 0.1932
Epoch 6/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 83s 92ms/step - accuracy: 0.9961 - loss: 0.0132 - val_accuracy: 0.9483 - val_loss: 0.2298
Epoch 7/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 82s 92ms/step - accuracy: 0.9966 - loss: 0.0102 - val_accuracy: 0.9510 - val_loss: 0.2486
Epoch 8/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 90s 109ms/step - accuracy: 0.9980 - loss: 0.0070 - val_accuracy: 0.9480 - val_loss: 0.2907
Epoch 9/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 74s 92ms/step - accuracy: 0.9979 - loss: 0.0063 - val_accuracy: 0.9486 - val_loss: 0.2779
Epoch 10/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 43s 90ms/step - accuracy: 0.9981 - loss: 0.0057 - val_accuracy: 0.9445 - val_loss: 0.3123

**Performance Metrices And Accuracy**

In [ ]:
y_pred=(model.predict(X_test) > 0.5).astype("int32")

464/464 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[4987, 2791],
       [4862, 2177]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.48349868394411827

In [ ]:
MAX_LEN = 200  # Maximum sequence length
padded_sequences = pad_sequences(sequences, maxlen=MAX_LEN)

In [ ]:
X = padded_sequences
y = df['Class']

In [ ]:
y_pred = (model.predict(X_test) > 0.5).astype("int32")

464/464 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step

In [ ]:
# Generate predictions
y_pred = (model.predict(X_test) > 0.5).astype("int32")

# Check accuracy or other metrics
from sklearn.metrics import accuracy_score, classification_report

# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

464/464 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step
Accuracy: 0.48349868394411827
Classification Report:
               precision    recall  f1-score   support

         0.0       0.51      0.64      0.57      7778
         1.0       0.44      0.31      0.36      7039

    accuracy                           0.48     14817
   macro avg       0.47      0.48      0.46     14817
weighted avg       0.47      0.48      0.47     14817